db:
  connection: '{connectionString:''http://_123'',username:''config'',password:''confpwd''}'
  host: 127.0.0.1
  port: 120
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
movieRating:
  value: 5
  list: 10,8,5,1
server:
  port: 8083
spring:
  application:
    name: rating-data-service
