db:
  connection: '{connectionString:''http://_789'',username:''cuis'',password:''cpwd''}'
  host: 127.0.0.1
  port: 120
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8084/eureka/
management:
  endpoints:
    web:
      exposure:
        include: '*'
movieRating:
  value: 5
  list: 13,14,15,16
server:
  port: 8083
spring:
  application:
    name: rating-data-service
